### ISSUE TITLE
Nest TargetDescriptor in same view as DetectionTargets

### ISSUE THREAD

**Issue by scmilee** [osu-cascades/batabase#40]
- add to list maintenance
- add target descriptor table

**Comment by nathanstruhs** [comment]
Created both tables with individual views. Will need to nest target descriptors under the appropriate detection target in index.

Update forms to handle creating both models under detection targets

**Comment by nathanstruhs** [comment]
Created nested table views. Will need to include target descriptors in the detection target create/edit forms.

**Comment by scmilee** [comment]
4b583b3 fixes this shizznazz
