### ISSUE TITLE
List Maintenance: Broad Habitat Class & Form

### ISSUE THREAD

**Issue by scmilee** [osu-cascades/batabase#75]

**Comment by nathanstruhs** [comment]
Per Roger:

"Broad Habitat and Detection Target are two different things and should have their own fields in the database. Broad Habitat is tied to the Sample Unit, while Detection Target is tied to the Deployment. Broad Habitat Form is nested in Broad Habitat Class. Depending how you decide to show that, but ultimately if you can show two fields; Broad Habitat Class and Broad Habitat Form on the Sample Units page, such as:
 
GRTS: 65599
Broad Habitat Class: Forest & Woodland
Broad Habitat Form: Cool Temperate Forest & Woodland
Regional Classifier: eastern Oregon
Agency: BLM
"

**Comment by scmilee** [comment]
nice
